import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Header from "../components/Header/Header";
import Footer from "../components/Footer/Footer";
import { cookies } from "next/headers";
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Joowon's Blog",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const res = cookies().get("mode");
  return (
    <html lang="ko">
      <body
        className={res != undefined && res.value === "dark" ? "dark" : ""}
      >
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}
